[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]

[profile.coverage]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
viaIR = true
optimizer = true
optimizer_runs = 1000
fuzz_runs = 1
fuzz_max_global_rejects = 65536
fuzz_max_local_rejects = 1024
fs_permissions = [{ access = "write", path = "./*" }]


[rpc_endpoints]
crossfi = "${CROSSFI_RPC}"
crossfi_dev = "${CROSSFI_DEV_RPC}"
crossfi_test = "${CROSSFI_TEST_RPC}"

[etherscan]
crossfi = { key = "no-key", url = "${CROSSFI_VERIFIER_URL}", chain = 4158}
crossfi_dev = { key = "ABCDEFG", url = "${CROSSFI_DEV_VERIFIER_URL}", chain = 4156}
crossfi_test = { key = "ABCDEFG", url = "${CROSSFI_TEST_VERIFIER_URL}", chain = 4157}


[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"
number_underscore = "thousands"
