[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"
]

[rpc_endpoints]
crossfi = "${CROSSFI_RPC}"
crossfi_dev = "${CROSSFI_DEV_RPC}"
crossfi_test = "${CROSSFI_TEST_RPC}"

[etherscan]
crossfi = { key = "no-key", url = "${CROSSFI_VERIFIER_URL}", chain = 4158 }
crossfi_dev = { key = "no-key", url = "${CROSSFI_DEV_VERIFIER_URL}", chain = 4156 }
crossfi_test = { key = "no-key", url = "${CROSSFI_TEST_VERIFIER_URL}", chain = 4157 }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
