[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
viaIR = true
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts"
]

[profile.coverage]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
viaIR = true
optimizer = true
optimizer_runs = 1000
fuzz_runs = 1
fuzz_max_global_rejects = 65536
fuzz_max_local_rejects = 1024

[rpc_endpoints]
local = "http://localhost:8545"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
